### ISSUE TITLE
Random throws of "invalid signature"

### ISSUE THREAD

**Issue by containerman17** [avalanche-typescript-subnet/avalanche-typescript-subnet#7]
I get this error message randomly:

```
--- FAIL: TestExecuteManyReadsAndWrites (0.05s)
    execute_test.go:132: 
                Error Trace:    /home/ilia/Projects/avalanche-typescript-subnet/avalanche-typescript-subnet/examples/typescriptvm/tests/integrationv2/actions/execute_test.go:132
                Error:          Received unexpected error:
                                failed to decode client response: invalid signature  http://127.0.0.1:36363/coreapi
                Test:           TestExecuteManyReadsAndWrites
```

In [examples/typescriptvm/tests/integrationv2/actions/execute_test.go#L76](https://github.com/avalanche-typescript-subnet/avalanche-typescript-subnet/blob/24c403f1673cd63c05c79122111bd92994e8dcc6/examples/typescriptvm/tests/integrationv2/actions/execute_test.go#L76), if I set `slotsToWrite` to 1, it succeeds almost every time. With `slotsToWrite` set to 2, the success rate is around 40%. With `slotsToWrite` set to 3, the success rate is also around 40%. It seems like there is a race condition or something similar.

**Comment by crrrazyden** [comment]
https://github.com/avalanche-typescript-subnet/avalanche-typescript-subnet/commit/62d1abe34067a709a2cbf076aec0c910a05c6b1c
This is the fix.

**Comment by containerman17** [comment]
Done here
